//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDS
    {
        public decimal CardNumber { get; set; }
        public string NameHolder { get; set; }
        public string Email { get; set; }
        public string Type { get; set; }
        public decimal Month { get; set; }
        public decimal Year { get; set; }
        public decimal Avaliable { get; set; }
        public string TipoDoc { get; set; }
        public decimal Doc { get; set; }
        public string Pass { get; set; }
    }
}
