//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int Id { get; set; }
        public string Fecha { get; set; }
        public Nullable<decimal> Doc { get; set; }
        public string Pass { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
